backend:
  name: github
  repo: dxw/playbook2
  branch: main
  open_authoring: true
media_library:
  name: 'disabled'
media_folder: "_images"
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: "root"
    label: "Index"
    files:
      - label: "Index page"
        name: "index"
        file: "index.markdown"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "guides"
    label: "Guides"
    folder: "_guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
